export const BrowserPlatformConfigurations = {
  ChromeAndroid: {
    appiumVersion: "1.20.2",
    deviceName: "Android Emulator",
    deviceOrientation: "portrait",
    shardTestFiles: true,
    maxInstances: 15,
    browserName: "Chrome",
    platformVersion: "8.0",
    platformName: "Android",
    chromeOptions: {
      args: ["--incognito"],
    },
  },
  SafariIOS: {
    appiumVersion: "1.22.3",
    deviceName: "iPhone Simulator",
    deviceOrientation: "portrait",
    shardTestFiles: true,
    maxInstances: 15,
    browserName: "Safari",
    platformVersion: "15.5",
    platformName: "iOS",
  },
  Firefox: {
    browserName: "firefox",
    shardTestFiles: true,
    maxInstances: 15,
    version: "88.0",
    platform: "Windows 10",
    screenResolution: "1920x1080",
    restartBrowserBetweenTests: true,
  },
  Edge: {
    browserName: "MicrosoftEdge",
    shardTestFiles: true,
    maxInstances: 15,
    version: "90",
    platform: "Windows 10",
    screenResolution: "1920x1080",
    edgeOptions: {
      args: ["--inprivate"],
    },
  },
  SafariDesktop: {
    browserName: "safari",
    version: "latest",
    platform: "macOS 12",
    screenResolution: "1280x960",
  },
  ChromeDesktop: {
    browserName: "chrome",
    shardTestFiles: true,
    maxInstances: 15,
    version: "99.0",
    platform: "Windows 10",
    screenResolution: "1920x1080",
    chromeOptions: {
      args: ["--incognito", "--start-maximized"],
    },
  },
};
